#!/bin/zsh

### DEFAULT SOFTWARE ###
# export TERM="alacritty"
export TERM='alacritty'
export EDITOR="nvim"
export VISUAL="nvim"
export READER="zathura"
export BROWSER="brave"
export PAGER="less"
export BAT_THEME="base16-256"
export DO_NOT_TRACK=1

export XDG_CONFIG_HOME=$HOME/.config

### scripts
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd ':')"
export PATH="$PATH:.emacs.d/bin"

### QT
export QT_QPA_PLATFORMTHEME=qt5ct

# DAT
### CODE & LANGS ###
export CODE_DIR=$HOME/codigo
export CODE_RSC=$CODE_DIR/resources
export CODE_PRJ=$CODE_DIR/projects
# rust
export RUSTUP_HOME=$HOME/.rustup
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
export CARGO_HOME=$HOME/.cargo
export PATH=$PATH:$CARGO_HOME/bin
source $HOME/.cargo/env
# go
export GOPATH=$CODE_PRJ/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
#ruby
export PATH=$PATH:$HOME/.gem/ruby/2.7.0/bin
#source "$HOME/.rvm/scripts/rvm"
# nim
export PATH=$PATH:$HOME/.nimble/bin
# python
export PATH=$PATH:$HOME/.local/share/python/python-language-server/output/bin/Release
# gdb (gef)
export GEF_RC=$HOME/.config/gef/gef.rc

[ -f "/home/tarsiec/.ghcup/env" ] && source "/home/tarsiec/.ghcup/env" # ghcup-env

### SOFTWARE ###
# starship.rs
# export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
# eval "$(starship init zsh)"
# source "$HOME/.local/share/zsh/prompts/powerlevel10k/powerlevel10k.zsh-theme"

### COMPLETION ###
setopt AUTO_CD
autoload -Uz compinit
compinit -i -d "${ZSH_COMPDUMP}"
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
setopt COMPLETE_IN_WORD
setopt ALWAYS_TO_END
setopt MENU_COMPLETE
setopt COMPLETE_ALIASES


# partial completion suggestions
zstyle ':completion:*' list-suffixes zstyle ':completion:*' expand prefix suffix 


### HISTORY ###
HISTFILE=$HOME/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

# setopt EXTENDED_HISTORY
# setopt APPEND_HISTORY
# setopt HIST_FIND_NO_DUPS
# setopt HIST_EXPIRE_DUPS_FIRST
# setopt HIST_VERIFY
# setopt SHARE_HISTORY
# setopt HIST_IGNORE_DUPS
# setopt INC_APPEND_HISTORY
# setopt HIST_REDUCE_BLANKS

### "PLUGINS" ###
# TODO loop to these instead of sourcing them all manuallyj
#source $HOME/.local/share/zsh/plugins/compleat/compleat.zsh
# source $HOME/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
# source $HOME/.local/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh
# source $HOME/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
# source $HOME/.local/share/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
# source $HOME/.local/share/zsh/plugins/vi-mode/vi-mode.zsh
# source $HOME/.local/share/zsh/plugins/git/git.zsh
# source $HOME/.local/share/zsh/plugins/emacs/emacs.zsh
# autoload -Uz add-zsh-hook


# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenu/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm

alias python3="python"
alias ytrss="python $HOME/codigo/repos/youtube_rss/youtube_rss.py"
alias getvid="youtube-dl --add-metadata --restrict-filenames -f bestvideo+bestaudio --merge-output-format mkv --all-subs"
alias getaudio="youtube-dl --add-metadata --restrict-filenames -x --audio-format best"
alias smi="sudo make install"
alias ls="exa"
alias l="exa -lag"
alias ll="exa -l"
alias lsize="exa -lags size"
alias lname="exa -lags name"
# alias ls="exa --icons"
# alias l="exa -lag --icons"
# alias ll="exa -l --icons"
# alias lsize="exa -lags size --icons"
# alias lname="exa -lags name --icons"
alias v="vim"
alias nv="nvim"
alias -g Z="| fzf"
alias -g C="| xclip -selection clipboard"
alias mv="mv -i -v"
alias mkdir="mkdir -p"
alias cp="cp -v"
alias grep="grep --color"
alias m="mocp"
alias haskell-language-server="haskell-language-server-wrapper"
alias screenshot="scrot"
alias newsboat="newsboat -C $HOME/.config/newsboat/config -u $HOME/.config/newsboat/urls -c $HOME/.config/newsboat/cache.db"
alias :q="exit"
alias :wq="exit"
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'
alias -g .......='../../../../../..'
alias -g ........='../../../../../../..'

# alias zathura="devour zathura"
# alias zathura="devour zathura"
# alias sxiv="devour sxiv"
# alias feh="devour feh"
# alias mpv="devour mpv"
# alias code="devour code"
# alias code-insiders="devour code-insiders"
# alias codium="devour codium"

# config aliases
alias vn="nvim $HOME/.config/nvim/init.vim"
alias vl="nvim $HOME/.config/nvim/init.lua"
alias vz="nvim $HOME/.config/zsh/zprofile"
alias vb="nvim $HOME/.config/bspwm/bspwmrc"
alias vs="nvim $HOME/.config/sxhkd/sxhkdrc"
alias vd="nvim $HOME/.config/dunst/dunstrc"
alias vp="nvim $HOME/.config/picom/picom.conf"

alias cdi="cd \`ls Z\`"
alias cfv="cd $HOME/.config/nvim"
alias cfz="cd $HOME/.config/zsh"
alias cfb="cd $HOME/.config/bspwm"
alias cfs="cd $HOME/.config/sxhkd"
alias cfd="cd $HOME/.config/dunst"
alias cfp="cd $HOME/.config/picom"
alias cfpfr="ssh root@tarsiec.com ./pullfromrepo.sh /var/www/tarsiec-site"

alias py="python"
alias ipy="ipython"

alias lo2pdf="libreoffice --headless --convert-to pdf"

alias D="devour"

bindkey -e
bindkey "jk" vi-cmd-mode

eval $(thefuck --alias)

[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:nmount;v:imgview'

# Z
. /usr/share/z/z.sh

