#!/bin/zsh


### ohmyzsh
#export ZSH="$HOME/.oh-my-zsh"

### DEFAULT SOFTWARE ###
export TERM="alacritty"
export EDITOR="emacs"
export VISUAL="emacs"
export READER="zathura"
export BROWSER="firefox"
export PAGER="less"

### scripts
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | paste -sd ':')"

export ZSH="/home/tlb/.oh-my-zsh"
### CODE & LANGS ###
export CODE_DIR=$HOME/code
export CODE_RSC=$CODE_DIR/resources
export CODE_PRJ=$CODE_DIR/projects
# rust
export RUSTUP_HOME=$HOME/.rustup
export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
export CARGO_HOME=$HOME/.cargo
export PATH=$PATH:$CARGO_HOME/bin
source $HOME/.cargo/env
# go
export GOPATH=$CODE_PRJ/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOBIN
#ruby
export PATH=$PATH:$HOME/.gem/ruby/2.7.0/bin
source "$HOME/.rvm/scripts/rvm"

[ -f "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env" ] && source "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env"

### SOFTWARE ###
# starship.rs
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
eval "$(starship init zsh)"
# source "$HOME/.local/share/zsh/prompts/powerlevel10k/powerlevel10k.zsh-theme"

### "PLUGINS" ###
source $HOME/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/.local/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source $HOME/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

eval "$(gh completion -s zsh)"

# oh my zsh
source $ZSH/oh-my-zsh.sh

plugins=(
	git
	golang
)

alias python3="python"
alias getvid="youtube-dl --restrict-filenames -f 22"
alias getaudio="youtube-dl --restrict-filenames -x --audio-format mp3"
alias dmi="doas make install"
alias dmci="doas make clean install"
alias drc="sudo make install & pkill dwm"
alias rcst="rm config.h & make & sudo make install"
alias ls="exa"
alias l="exa -lag"
alias lsize="exa -lags size"
alias lname="exa -lags name"
alias v="vim"
alias nv="nvim"
alias -g Z="| fzf"
alias mv="mv -i"
alias m="mocp"
alias screenshot="scrot"
alias newsboat="newsboat -C $HOME/.config/newsboat/config -u $HOME/.config/newsboat/urls -c $HOME/.config/newsboat/cache.db"
