#! /bin/sh

xrdb .Xresources &
setxkbmap gb &
picom --config ~/.config/picom/picom.conf &
xwallpaper --zoom ~/.config/wall.jpg &
sxhkd /home/tlb/.config/sxhkd/sxhkdrc &
dropbox &
dunst ~/.config/dunst/dunstrc &
launchbar &
setxkbmap -option caps:ctrl_modifier gb
nm-applet &
xclickroot -r xmenu.sh

#bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor -d misc dev web irc git sys doc pic media

bspc config focused_border_color "#b58900"
bspc config normal_border_color  "#002b36"
bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          0

bspc rule -a Gimp desktop='^7' follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
