#!/bin/sh

# bspc config border_width		1
bspc config border_width		1
bspc config window_gap			0

bspc config split_ratio			0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true
bspc config top_padding			0
bspc config single_monocle		true

# pkill dunst
if [ "$(pgrep dunst)" ]; then
	pkill dunst
fi
dunst -c ~/.config/dunst/dunstrc &
xwallpaper --zoom ~/.config/wall* &
launch_polybar &

# Start flavours
bspc config focused_border_color '#f0c674'
bspc config normal_border_color '#1d1f21'
# End flavours
