#! /bin/sh

xwallpaper --zoom ~/.config/wall.jpg &
betterlockscreen -u ~/.config/wall.jpg &
sxhkd &
pkill picom &
picom --config ~/.config/picom/picom.conf &
xfce4-power-manager &
xset +fp /home/tlb/.local/share/fonts &
xset fp rehash &
calcurse --daemon &
launchbar &
dropbox &

bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor -d home dev net git files doc pic vid mus

bspc config focused_border_color "#aab1be"
bspc config normal_border_color  "#262931"
bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          0

bspc rule -a Gimp desktop='^7' follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
