#! /bin/sh

xrdb .Xresources
setxkbmap gb
picom --config ~/.config/picom/picom.conf &
sxhkd /home/tlb/.config/sxhkd/sxhkdrc &
calcurse --daemon &
mpd &
setxkbmap -option caps:ctrl_modifier gb

#bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor -d misc dev web chat git sys doc pic media
#bspc monitor -d 1 2 3 4 5 6

bspwmlooks



bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
