#!/bin/sh

bspc config border_width		 1
bspc config window_gap			 0

bspc config split_ratio			0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true
bspc config top_padding			0
bspc config single_monocle		true

# Start flavours
bspc config focused_border_color "#b58900"
bspc config normal_border_color "#002b36"
# End flavours
